Changed admin mailbox format to Maildir, to simplify migration path. Refs #1669, #1622

diff --git a/root/etc/e-smith/events/actions/nethserver-mail-server-init-system-users b/root/etc/e-smith/events/actions/nethserver-mail-server-init-system-users
--- a/root/etc/e-smith/events/actions/nethserver-mail-server-init-system-users
+++ b/root/etc/e-smith/events/actions/nethserver-mail-server-init-system-users
@@ -28,16 +28,22 @@
 # only owner has r/w access to files created by this scritpt:
 umask 077
 
-# disable noclobber flag:
+# disable noclobber flag::
 set +C 
+
+# exit on errors
+set -e
+
+#
+# Create a temporary directory as to fake a MAIL HOME
+#
+TMP_MAILDIR=`mktemp -d /var/tmp/nethserver-mail-server-init-system-users.XXXXXXXXXXXXXX`
+trap "rm -rf ${TMP_MAILDIR}" EXIT
+chown vmail.vmail ${TMP_MAILDIR}
 
 for USER in `cut -d : -f 1 /etc/dovecot/system-users`; do
 
-    MAIL_HOME="/var/lib/vmail/user/${USER}"
-
     MBOX_SRC="/var/mail/${USER}"
-    MBOX_DST="${MAIL_HOME}/mbox"
-    
 
     # skip unknown users
     id "${USER}" &>/dev/null || continue
@@ -48,14 +54,16 @@ for USER in `cut -d : -f 1 /etc/dovecot/system-users`; do
     # skip empty files
     [ -s "${MBOX_SRC}" ] || continue
 
-    # create MAIL_HOME directory setting perms 700
-    ! [ -d "${MAIL_HOME}" ] && mkdir -p -m 700 "${MAIL_HOME}"
+    echo "[INFO] Migrating ${USER} mailbox from ${MBOX_SRC}";
 
-    echo "Migrating ${USER} mailbox: ${MBOX_SRC} => ${MBOX_DST}";
+    # Copy to the temporary dir and fix permissions:
+    cp "${MBOX_SRC}" "${TMP_MAILDIR}/INBOX" && chown vmail.vmail "${TMP_MAILDIR}/INBOX"
 
-    # copy original mailbox then truncate it
-    cat "${MBOX_SRC}" >> "${MBOX_DST}" && echo -n "" > "${MBOX_SRC}"
-    chown -R vmail.vmail "${MAIL_HOME}"
+    # Import data then truncate the original mailbox:
+    /usr/bin/doveadm import -u "${USER}" "mbox:${TMP_MAILDIR}:INBOX=${TMP_MAILDIR}/INBOX" '' ALL  \
+	&& echo -n "" > "${MBOX_SRC}"
 
+    # Subscribe INBOX folder:
+    /usr/bin/doveadm mailbox subscribe -u "${USER}" INBOX
 
 done
